### ISSUE TITLE
Video format

### ISSUE THREAD

**Issue by HarshRaj-I** [eppic/ytBATCH#3]
how to set default format to bv+ba/b for downloading video

**Comment by eppic** [comment]
ytBATCH uses a default way to download anything to keep it simple. So at least right now, it is not an option - as i dont have any time to actively work on this project right now. 
[VideoDLnew.txt](https://github.com/eppic/ytBATCH/files/8720970/VideoDLnew.txt)
This is a modified version of VideoDL.bat that supports bv+ba/b.
Go to ytBATCH\bin\VideoDL.bat and replace it with this text file (rename it to VideoDL.bat !!!)
Hope this helped.
