### ISSUE TITLE
[Question] How to download a Youtube Playlist concurrently

### ISSUE THREAD

**Issue by candrapersada** [eppic/ytBATCH#5]
How can I download a YouTube playlist concurrently/multithreaded? I've tried a lot around, but it's always doing single downloads which is kinda wasted for people with a greater bandwidth.

**Comment by eppic** [comment]
The goal of ytBATCH is keeping everything as simple as possible. This means being limited to the tools yt-dlp provides without adding other programs. Sadly, yt-dlp is not capable of concurrent downloads atm.
