### ISSUE TITLE
Prepend Playlist_index

### ISSUE THREAD

**Issue by Bartholomue** [eppic/ytBATCH#6]
Would it be possible to add to the options the ability to prepend the playlist index to a file name? I see this is an option with youtube-dl, and it would be great for ordering playlists in the appropriate sequence.

**Comment by eppic** [comment]
The code that tells ytBATCH where to store and how to name files is always the same for every download and can not be set seperately atm. I will tackle this problem in the near future, this includes redoing some of the core code of ytBATCH.
