### ISSUE TITLE
Cannot Populate Queue List

### ISSUE THREAD

**Issue by Bartholomue** [eppic/ytBATCH#8]
If you enter a link, press "q" to set queuing to true, then press "a" for audio, it looks like ytBatch is supposed to be creating a list of files to download.
After adding 10 links, though, trying to start the download fails, and the queue list batch file is empty.

**Comment by eppic** [comment]
Do you have ytBATCH installed somewhere with limited access? Maybe ytBATCH is not allowed to write to that location.
Do the links you use have "&" in them or other notable characters? These cause ytBATCH to not always work properly.

**Comment by Bartholomue** [comment]
I have ytBatch on my data drive which has no restrictions. It's the drive I put stuff on because I don't want to be annoyed by user account control, so it shouldn't have write issues -- it is able to writee the mp3 files to the dl folder in the same area.

**Comment by eppic** [comment]
Try putting this in the root of ytBATCH and rename it to *.bat - Then start ytBATCH and run the Queue and see if it works.
[QueueList.txt](https://github.com/eppic/ytBATCH/files/9444009/QueueList.txt)

**Comment by Bartholomue** [comment]
Running this queue list did work. But when I try to add my own items with the batch interface, it just creates an empty queuelist.bat file, no matter how many entries I've made. I'll try again with five and see if they populate.

**Comment by Bartholomue** [comment]
Strange. It worked for the videos I tested, but did not work for the videos I tried the other day. I'll close the issue until I can narrow down the reason -- possibly format?
